default_source = "github"
dependencies = [
    {path = "skills/brand-guidelines", type = "skill"},
    {handle = "microsoft/playwright-cli/playwright-cli", type = "skill"},
    {path = "skills/release", type = "skill"},
]

[[source]]
name = "github"
type = "git"
url = "https://github.com/{owner}/{repo}.git"
